// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVue.DAL;

namespace WebVue.Migrations
{
    [DbContext(typeof(BigBagDbContext))]
    [Migration("20230908221759_SeedTestData")]
    partial class SeedTestData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Programy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Uzivatelia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zariadenia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = ""
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CasVazenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CasVycitania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Den")
                        .HasColumnType("int");

                    b.Property<int?>("Hodiny")
                        .HasColumnType("int");

                    b.Property<int?>("Mesiac")
                        .HasColumnType("int");

                    b.Property<int?>("Minuty")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramCislo")
                        .HasColumnType("int");

                    b.Property<string>("ProgramNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rok")
                        .HasColumnType("int");

                    b.Property<int?>("UzivatelCislo")
                        .HasColumnType("int");

                    b.Property<string>("UzivatelNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vaha")
                        .HasColumnType("float");

                    b.Property<int?>("ZariadenieCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Zaznamy");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            CasVazenia = new DateTime(2023, 9, 9, 0, 17, 58, 810, DateTimeKind.Local).AddTicks(5230),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(8556),
                            ProgramCislo = 1,
                            ProgramNazov = "Program1",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 32,
                            CasVazenia = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9092),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9109),
                            ProgramCislo = 1,
                            ProgramNazov = "Program1",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 91.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 33,
                            CasVazenia = new DateTime(2023, 9, 11, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9115),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9131),
                            ProgramCislo = 2,
                            ProgramNazov = "Program2",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 34,
                            CasVazenia = new DateTime(2023, 9, 12, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9136),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9140),
                            ProgramCislo = 2,
                            ProgramNazov = "Program2",
                            UzivatelCislo = 2,
                            UzivatelNazov = "Uzivatel2",
                            Vaha = 90.0,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 35,
                            CasVazenia = new DateTime(2023, 9, 15, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9145),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9148),
                            ProgramCislo = 3,
                            ProgramNazov = "Program3",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 85.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 36,
                            CasVazenia = new DateTime(2023, 9, 16, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9153),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9156),
                            ProgramCislo = 1,
                            ProgramNazov = "Program1",
                            UzivatelCislo = 2,
                            UzivatelNazov = "Uzivatel2",
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 37,
                            CasVazenia = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9160),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9164),
                            ProgramCislo = 2,
                            ProgramNazov = "Program2",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 92.0,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 38,
                            CasVazenia = new DateTime(2023, 9, 13, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9168),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9171),
                            ProgramCislo = 1,
                            ProgramNazov = "Program1",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 91.0,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 39,
                            CasVazenia = new DateTime(2023, 9, 14, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9175),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9179),
                            ProgramCislo = 3,
                            ProgramNazov = "Program3",
                            UzivatelCislo = 3,
                            UzivatelNazov = "Uzivatel3",
                            Vaha = 91.5,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 40,
                            CasVazenia = new DateTime(2023, 9, 10, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9183),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9187),
                            ProgramCislo = 3,
                            ProgramNazov = "Program3",
                            UzivatelCislo = 1,
                            UzivatelNazov = "Uzivatel1",
                            Vaha = 90.5,
                            ZariadenieCislo = 3,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 41,
                            CasVazenia = new DateTime(2023, 9, 10, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9191),
                            CasVycitania = new DateTime(2023, 9, 9, 0, 17, 58, 813, DateTimeKind.Local).AddTicks(9194),
                            ProgramCislo = 3,
                            ProgramNazov = "Program3",
                            UzivatelCislo = 3,
                            UzivatelNazov = "Uzivatel3",
                            Vaha = 92.5,
                            ZariadenieCislo = 3,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Programy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Uzivatelia")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Navigation("Programy");

                    b.Navigation("Uzivatelia");

                    b.Navigation("Zaznamy");
                });
#pragma warning restore 612, 618
        }
    }
}
