// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVue.DAL;

namespace WebVue.Migrations
{
    [DbContext(typeof(BigBagDbContext))]
    [Migration("20230904211928_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("ProgramVyroby");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 4,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 5,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 6,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Uzivatel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 4,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 5,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 6,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zariadenie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cas")
                        .HasColumnType("datetime2");

                    b.Property<int>("Den")
                        .HasColumnType("int");

                    b.Property<int>("Hodiny")
                        .HasColumnType("int");

                    b.Property<int>("Mesiac")
                        .HasColumnType("int");

                    b.Property<int>("Minuty")
                        .HasColumnType("int");

                    b.Property<int>("ProgramCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Rok")
                        .HasColumnType("int");

                    b.Property<int>("UzivatelCislo")
                        .HasColumnType("int");

                    b.Property<int?>("UzivatelId")
                        .HasColumnType("int");

                    b.Property<float>("Vaha")
                        .HasColumnType("real");

                    b.Property<int>("ZariadenieCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UzivatelId");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Zaznam");
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Programy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany()
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.HasOne("WebVue.Models.ProgramVyroby", "Program")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ProgramId");

                    b.HasOne("WebVue.Models.Uzivatel", "Uzivatel")
                        .WithMany("Zaznamy")
                        .HasForeignKey("UzivatelId");

                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Program");

                    b.Navigation("Uzivatel");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Navigation("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Navigation("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Navigation("Programy");

                    b.Navigation("Zaznamy");
                });
#pragma warning restore 612, 618
        }
    }
}
