// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVue.DAL;

namespace WebVue.Migrations
{
    [DbContext(typeof(BigBagDbContext))]
    [Migration("20230908221738_SeedInitial")]
    partial class SeedInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Programy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Uzivatelia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zariadenia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = ""
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CasVazenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CasVycitania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Den")
                        .HasColumnType("int");

                    b.Property<int?>("Hodiny")
                        .HasColumnType("int");

                    b.Property<int?>("Mesiac")
                        .HasColumnType("int");

                    b.Property<int?>("Minuty")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramCislo")
                        .HasColumnType("int");

                    b.Property<string>("ProgramNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rok")
                        .HasColumnType("int");

                    b.Property<int?>("UzivatelCislo")
                        .HasColumnType("int");

                    b.Property<string>("UzivatelNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vaha")
                        .HasColumnType("float");

                    b.Property<int?>("ZariadenieCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Programy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Uzivatelia")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Navigation("Programy");

                    b.Navigation("Uzivatelia");

                    b.Navigation("Zaznamy");
                });
#pragma warning restore 612, 618
        }
    }
}
