// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVue.DAL;

namespace WebVue.Migrations
{
    [DbContext(typeof(BigBagDbContext))]
    partial class BigBagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Programy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Uzivatelia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 8,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 9,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 10,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 11,
                            Cislo = 10,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 12,
                            Cislo = 11,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 13,
                            Cislo = 12,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 14,
                            Cislo = 13,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 15,
                            Cislo = 14,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 16,
                            Cislo = 15,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 17,
                            Cislo = 16,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 18,
                            Cislo = 17,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 19,
                            Cislo = 18,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 20,
                            Cislo = 19,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 21,
                            Cislo = 20,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 22,
                            Cislo = 21,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 23,
                            Cislo = 22,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 24,
                            Cislo = 23,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 25,
                            Cislo = 24,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 26,
                            Cislo = 25,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 27,
                            Cislo = 26,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 28,
                            Cislo = 27,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 29,
                            Cislo = 28,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 30,
                            Cislo = 29,
                            Nazov = "",
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 31,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 32,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 33,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 34,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 35,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 36,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 37,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 38,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 39,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 40,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 41,
                            Cislo = 10,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 42,
                            Cislo = 11,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 43,
                            Cislo = 12,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 44,
                            Cislo = 13,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 45,
                            Cislo = 14,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 46,
                            Cislo = 15,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 47,
                            Cislo = 16,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 48,
                            Cislo = 17,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 49,
                            Cislo = 18,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 50,
                            Cislo = 19,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 51,
                            Cislo = 20,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 52,
                            Cislo = 21,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 53,
                            Cislo = 22,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 54,
                            Cislo = 23,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 55,
                            Cislo = 24,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 56,
                            Cislo = 25,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 57,
                            Cislo = 26,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 58,
                            Cislo = 27,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 59,
                            Cislo = 28,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 60,
                            Cislo = 29,
                            Nazov = "",
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 61,
                            Cislo = 0,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 62,
                            Cislo = 1,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 63,
                            Cislo = 2,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 64,
                            Cislo = 3,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 65,
                            Cislo = 4,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 66,
                            Cislo = 5,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 67,
                            Cislo = 6,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 68,
                            Cislo = 7,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 69,
                            Cislo = 8,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 70,
                            Cislo = 9,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 71,
                            Cislo = 10,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 72,
                            Cislo = 11,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 73,
                            Cislo = 12,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 74,
                            Cislo = 13,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 75,
                            Cislo = 14,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 76,
                            Cislo = 15,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 77,
                            Cislo = 16,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 78,
                            Cislo = 17,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 79,
                            Cislo = 18,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 80,
                            Cislo = 19,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 81,
                            Cislo = 20,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 82,
                            Cislo = 21,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 83,
                            Cislo = 22,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 84,
                            Cislo = 23,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 85,
                            Cislo = 24,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 86,
                            Cislo = 25,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 87,
                            Cislo = 26,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 88,
                            Cislo = 27,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 89,
                            Cislo = 28,
                            Nazov = "",
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 90,
                            Cislo = 29,
                            Nazov = "",
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zariadenia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 0,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 1,
                            Nazov = ""
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 2,
                            Nazov = ""
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CasVazenia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CasVycitania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Den")
                        .HasColumnType("int");

                    b.Property<int?>("Hodiny")
                        .HasColumnType("int");

                    b.Property<int?>("Mesiac")
                        .HasColumnType("int");

                    b.Property<int?>("Minuty")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramCislo")
                        .HasColumnType("int");

                    b.Property<string>("ProgramNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rok")
                        .HasColumnType("int");

                    b.Property<int?>("UzivatelCislo")
                        .HasColumnType("int");

                    b.Property<string>("UzivatelNazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Vaha")
                        .HasColumnType("float");

                    b.Property<int?>("ZariadenieCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Programy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Uzivatelia")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Navigation("Programy");

                    b.Navigation("Uzivatelia");

                    b.Navigation("Zaznamy");
                });
#pragma warning restore 612, 618
        }
    }
}
