// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVue.DAL;

namespace WebVue.Migrations
{
    [DbContext(typeof(BigBagDbContext))]
    partial class BigBagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("ProgramVyroby");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 4,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 5,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 6,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Uzivatel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 4,
                            Cislo = 4,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 5,
                            Cislo = 5,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 6,
                            Cislo = 6,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cislo")
                        .HasColumnType("int");

                    b.Property<string>("Nazov")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Zariadenie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cislo = 1
                        },
                        new
                        {
                            Id = 2,
                            Cislo = 2
                        },
                        new
                        {
                            Id = 3,
                            Cislo = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Cas")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Den")
                        .HasColumnType("int");

                    b.Property<int?>("Hodiny")
                        .HasColumnType("int");

                    b.Property<int?>("Mesiac")
                        .HasColumnType("int");

                    b.Property<int?>("Minuty")
                        .HasColumnType("int");

                    b.Property<int>("ProgramCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int?>("Rok")
                        .HasColumnType("int");

                    b.Property<int>("UzivatelCislo")
                        .HasColumnType("int");

                    b.Property<int?>("UzivatelId")
                        .HasColumnType("int");

                    b.Property<double>("Vaha")
                        .HasColumnType("float");

                    b.Property<int>("ZariadenieCislo")
                        .HasColumnType("int");

                    b.Property<int?>("ZariadenieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("UzivatelId");

                    b.HasIndex("ZariadenieId");

                    b.ToTable("Zaznam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cas = new DateTime(2023, 9, 4, 23, 54, 29, 76, DateTimeKind.Local).AddTicks(2050),
                            ProgramCislo = 1,
                            ProgramId = 1,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cas = new DateTime(2023, 9, 4, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6670),
                            ProgramCislo = 1,
                            ProgramId = 1,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 91.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Cas = new DateTime(2023, 9, 6, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6715),
                            ProgramCislo = 2,
                            ProgramId = 2,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 4,
                            Cas = new DateTime(2023, 9, 7, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6733),
                            ProgramCislo = 2,
                            ProgramId = 2,
                            UzivatelCislo = 2,
                            UzivatelId = 2,
                            Vaha = 90.0,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 5,
                            Cas = new DateTime(2023, 9, 10, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6739),
                            ProgramCislo = 3,
                            ProgramId = 3,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 85.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 6,
                            Cas = new DateTime(2023, 9, 11, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6743),
                            ProgramCislo = 1,
                            ProgramId = 1,
                            UzivatelCislo = 2,
                            UzivatelId = 2,
                            Vaha = 90.5,
                            ZariadenieCislo = 1,
                            ZariadenieId = 1
                        },
                        new
                        {
                            Id = 7,
                            Cas = new DateTime(2023, 9, 4, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6747),
                            ProgramCislo = 2,
                            ProgramId = 2,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 92.0,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 8,
                            Cas = new DateTime(2023, 9, 8, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6751),
                            ProgramCislo = 1,
                            ProgramId = 1,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 91.0,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 9,
                            Cas = new DateTime(2023, 9, 9, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6756),
                            ProgramCislo = 3,
                            ProgramId = 3,
                            UzivatelCislo = 3,
                            UzivatelId = 3,
                            Vaha = 91.5,
                            ZariadenieCislo = 2,
                            ZariadenieId = 2
                        },
                        new
                        {
                            Id = 10,
                            Cas = new DateTime(2023, 9, 5, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6760),
                            ProgramCislo = 3,
                            ProgramId = 3,
                            UzivatelCislo = 1,
                            UzivatelId = 1,
                            Vaha = 90.5,
                            ZariadenieCislo = 3,
                            ZariadenieId = 3
                        },
                        new
                        {
                            Id = 11,
                            Cas = new DateTime(2023, 9, 5, 23, 54, 29, 79, DateTimeKind.Local).AddTicks(6764),
                            ProgramCislo = 3,
                            ProgramId = 3,
                            UzivatelCislo = 3,
                            UzivatelId = 3,
                            Vaha = 92.5,
                            ZariadenieCislo = 3,
                            ZariadenieId = 3
                        });
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Programy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany()
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.Zaznam", b =>
                {
                    b.HasOne("WebVue.Models.ProgramVyroby", "Program")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ProgramId");

                    b.HasOne("WebVue.Models.Uzivatel", "Uzivatel")
                        .WithMany("Zaznamy")
                        .HasForeignKey("UzivatelId");

                    b.HasOne("WebVue.Models.Zariadenie", "Zariadenie")
                        .WithMany("Zaznamy")
                        .HasForeignKey("ZariadenieId");

                    b.Navigation("Program");

                    b.Navigation("Uzivatel");

                    b.Navigation("Zariadenie");
                });

            modelBuilder.Entity("WebVue.Models.ProgramVyroby", b =>
                {
                    b.Navigation("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.Uzivatel", b =>
                {
                    b.Navigation("Zaznamy");
                });

            modelBuilder.Entity("WebVue.Models.Zariadenie", b =>
                {
                    b.Navigation("Programy");

                    b.Navigation("Zaznamy");
                });
#pragma warning restore 612, 618
        }
    }
}
